version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.7.3
  - dependency-name: webpacker
    versions:
    - 5.2.1
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: capybara
    versions:
    - 3.35.1
